service: aws-auth

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  getUsers:
    handler: user/userHandler.getUsers
    events:
      - http:
          path: users
          method: get
          cors: true
  
  signup:
    handler: auth/signupHandler.signup
    events:
      - http:
          path: signup
          method: post
          cors:
            origin: '*'

  register:
    handler: auth/registerHandler.register
    events:
      - http:
          path: register
          method: post
          cors:
            origin: '*'

  login:
    handler: auth/loginHandler.login
    events:
      - http:
          path: login
          method: post
          cors:
            origin: '*'

  signin:
    handler: auth/signinHandler.signin
    events:
      - http:
          path: signin
          method: post
          cors:
            origin: '*'
  
  verify-token:
    handler: auth/verify.auth

  profile:
    handler: auth/profileHandler.profile
    events:
      - http:
          path: profile
          method: get
          cors:
            origin: '*'
          authorizer: verify-token

plugins:
  - serverless-offline