service: aws-auth

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    DB: ${self:custom.secrets.DB}

functions:
  getUsers:
    handler: user/userHandler.getUsers
    events:
      - http:
          path: users
          method: get
          cors: true